### ISSUE TITLE
Fatal error: Uncaught TypeError: Cannot assign null to property

### ISSUE THREAD

**Issue by dragomano** [jdarwood007/smfmod_devtools#8]
The error occurs when you switch the interface language from English to any other language.

```php
Fatal error: Uncaught TypeError: Cannot assign null to property DevTools::$txt of type array in D:\OSP\home\smf-80.local\public_html\Sources\DevTools.php:42 Stack trace: #0 D:\OSP\home\smf-80.local\public_html\Sources\Subs.php(5964): DevTools->__construct() #1 D:\OSP\home\smf-80.local\public_html\Sources\Subs.php(5762): call_helper('DevTools::hook_...', true) #2 D:\OSP\home\smf-80.local\public_html\Sources\Subs.php(4081): call_integration_hook('integrate_redir...', Array) #3 D:\OSP\home\smf-80.local\public_html\Sources\Load.php(940): redirectexit('http://smf-80.l...') #4 D:\OSP\home\smf-80.local\public_html\index.php(221): loadUserSettings() #5 D:\OSP\home\smf-80.local\public_html\index.php(191): smf_main() #6 {main} thrown in D:\OSP\home\smf-80.local\public_html\Sources\DevTools.php on line 42
```

Possible fix: replace `private array $txt;` with `private ?array $txt;` in DevTools.php

**Comment by jdarwood007** [comment]
Yea this occurs because prior to loading $txt, we redirectexit for changing the language and the system can't startup properly.  Could also be fixed in SMF by defining `$txt = [];` sooner
